server:
  port: 9200
spring:
  main:
     allow-bean-definition-overriding: true
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    database: MYSQL
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/clients_db?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
    username: root
    password: admin
  zipkin:
    base-url: http://localhost:9411
  sleuth:
    sampler:
      probability: 1
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
      
feign:
  hystrix:
    enabled: true
   
keycloak:
  realm: formation-ms
  auth-server-url: http://localhost:8080/auth
  resource: client-app
  credentials:
    secret: b5f3ff40-ea57-4b08-bda8-e676ee5edb7a
  principal-attribute: preferred_username
  bearer-only: true

swagger-ui:
  client: swagger-ui
  secret: 6c37705a-d860-480d-b6b2-74676a7129f8
