server:
  port: 9000
spring:
  application:
    name: client-service
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    database: MYSQL
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://${MYSQL_HOST}:3306/clients_db?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
    username: root
    password:

eureka:
 client:
   serviceUrl:
    defaultZone: http://localhost:8761/eureka/

keycloak:
    realm: formation-ms
    auth-server-url: http://localhost:8080/auth
    resource: client-app
    credentials:
      secret: d58d9e7e-2d7f-4359-9fb8-08e96d535ab3
    principal-attribute: preferred_username
    bearer-only: true

feign:
 hystrix:
     enabled: false

swagger-ui:
  client: swagger-ui
  secret: fe72f81f-85f0-478b-b8fb-64d7af398aaf
